### PR TITLE
Changing index.js for index.ts

### PR DESCRIPTION
**Pull request by andrelmlins**
Hello @hrutvikpatel , this project is fantastic, thanks...

When using the library with typescript, the types were not being identified. I believe this happens because of index.js.

### CODE REVIEW

**Comment by hrutvikpatel** [comment]
> Hello @hrutvikpatel , this project is fantastic, thanks...
> 
> When using the library with typescript, the types were not being identified. I believe this happens because of index.js.

Sorry I have been really busy with exams. Let's try what you said, I will try to get this published asap.

**Comment by andrelmlins** [comment]
All good, thank you so much

**Comment by hrutvikpatel** [comment]
> Hello @hrutvikpatel , this project is fantastic, thanks...
> 
> When using the library with typescript, the types were not being identified. I believe this happens because of index.js.

Oh, I think I remember why I kept it index.js its because the package.json has to reference the init file so src/index.ts but that didn't work. So I made it src/index.js which did work.

Let me test it.

**Comment by hrutvikpatel** [comment]
@andrelmlins I just tested it out locally. Made one change to the package.json file too.
In case you want to replicate my steps. I just did this:
- ran `yarn` in the example folder
- ran `pod install` in example/ios
- opened the .workspace folder using Xcode and tested it on the app

Seems to work fine. After I publish it in the next few minutes let me know if you face any other issues.

**Comment by hrutvikpatel** [comment]
@andrelmlins published

**Comment by andrelmlins** [comment]
It works perfectly, thank you again!

**Comment by hrutvikpatel** [comment]
No worries lol I appreciate the fact that at least this is useful for someone!

**Pull request merged**
